### ISSUE TITLE
Upgrade to ruby >=2.4.0?

### ISSUE THREAD

**Issue by cdrrazan** [philnash/philna.sh#1]
As the official docs says, 

```
    Ruby 2.3 series
    Currently in security maintenance phase. We will never backport any bug fixes to 2.3 except security 
    fixes. If a critical security issue is found, we will release an urgent fix for it. We are planning to end the 
    support of the Ruby 2.3 series at the end of March 2019.
```
Have you sir planned to upgrade to 2.4 or latest ruby version for this blog?

**Comment by philnash** [comment]
You know, I probably was going to. It's not been a pressing issue as Jekyll is still working fine generating the site for now.

Why do you ask?

**Comment by cdrrazan** [comment]
I have been following your blog since i found out and have made a site about me inspired from this theme and i just found out the docs stating this. So just a friendly reminder.

**Comment by philnash** [comment]
Fair enough. I'll see what I can do about moving this onto 2.6.

**Comment by philnash** [comment]
The site is now generated happily by Ruby 2.6.0: https://github.com/philnash/philna.sh/blob/master/.ruby-version
